// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EnvironmentNodeFirewallInitParameters struct {

	// Enable host firewall rules (defaults to `true`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Log level for forwarded traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	LogLevelForward *string `json:"logLevelForward,omitempty" tf:"log_level_forward,omitempty"`

	// Log level for incoming traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	LogLevelIn *string `json:"logLevelIn,omitempty" tf:"log_level_in,omitempty"`

	// Log level for outgoing traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	LogLevelOut *string `json:"logLevelOut,omitempty" tf:"log_level_out,omitempty"`

	// Enable NDP - Neighbor Discovery Protocol (defaults to `true`).
	Ndp *bool `json:"ndp,omitempty" tf:"ndp,omitempty"`

	// Maximum number of tracked connections (defaults to `262144`). Minimum value is `32768`.
	NfConntrackMax *float64 `json:"nfConntrackMax,omitempty" tf:"nf_conntrack_max,omitempty"`

	// Conntrack established timeout in seconds (defaults to `432000` - 5 days). Minimum value is `7875`.
	NfConntrackTCPTimeoutEstablished *float64 `json:"nfConntrackTcpTimeoutEstablished,omitempty" tf:"nf_conntrack_tcp_timeout_established,omitempty"`

	// Enable nftables based firewall (tech preview, defaults to `false`).
	Nftables *bool `json:"nftables,omitempty" tf:"nftables,omitempty"`

	// The cluster node name.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`

	// Enable SMURFS filter (defaults to `true`).
	Nosmurfs *bool `json:"nosmurfs,omitempty" tf:"nosmurfs,omitempty"`

	// Log level for SMURFS filter. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	SmurfLogLevel *string `json:"smurfLogLevel,omitempty" tf:"smurf_log_level,omitempty"`

	// Log level for illegal tcp flags filter. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	TCPFlagsLogLevel *string `json:"tcpFlagsLogLevel,omitempty" tf:"tcp_flags_log_level,omitempty"`
}

type EnvironmentNodeFirewallObservation struct {

	// Enable host firewall rules (defaults to `true`).
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Log level for forwarded traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	LogLevelForward *string `json:"logLevelForward,omitempty" tf:"log_level_forward,omitempty"`

	// Log level for incoming traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	LogLevelIn *string `json:"logLevelIn,omitempty" tf:"log_level_in,omitempty"`

	// Log level for outgoing traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	LogLevelOut *string `json:"logLevelOut,omitempty" tf:"log_level_out,omitempty"`

	// Enable NDP - Neighbor Discovery Protocol (defaults to `true`).
	Ndp *bool `json:"ndp,omitempty" tf:"ndp,omitempty"`

	// Maximum number of tracked connections (defaults to `262144`). Minimum value is `32768`.
	NfConntrackMax *float64 `json:"nfConntrackMax,omitempty" tf:"nf_conntrack_max,omitempty"`

	// Conntrack established timeout in seconds (defaults to `432000` - 5 days). Minimum value is `7875`.
	NfConntrackTCPTimeoutEstablished *float64 `json:"nfConntrackTcpTimeoutEstablished,omitempty" tf:"nf_conntrack_tcp_timeout_established,omitempty"`

	// Enable nftables based firewall (tech preview, defaults to `false`).
	Nftables *bool `json:"nftables,omitempty" tf:"nftables,omitempty"`

	// The cluster node name.
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`

	// Enable SMURFS filter (defaults to `true`).
	Nosmurfs *bool `json:"nosmurfs,omitempty" tf:"nosmurfs,omitempty"`

	// Log level for SMURFS filter. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	SmurfLogLevel *string `json:"smurfLogLevel,omitempty" tf:"smurf_log_level,omitempty"`

	// Log level for illegal tcp flags filter. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	TCPFlagsLogLevel *string `json:"tcpFlagsLogLevel,omitempty" tf:"tcp_flags_log_level,omitempty"`
}

type EnvironmentNodeFirewallParameters struct {

	// Enable host firewall rules (defaults to `true`).
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Log level for forwarded traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	// +kubebuilder:validation:Optional
	LogLevelForward *string `json:"logLevelForward,omitempty" tf:"log_level_forward,omitempty"`

	// Log level for incoming traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	// +kubebuilder:validation:Optional
	LogLevelIn *string `json:"logLevelIn,omitempty" tf:"log_level_in,omitempty"`

	// Log level for outgoing traffic. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	// +kubebuilder:validation:Optional
	LogLevelOut *string `json:"logLevelOut,omitempty" tf:"log_level_out,omitempty"`

	// Enable NDP - Neighbor Discovery Protocol (defaults to `true`).
	// +kubebuilder:validation:Optional
	Ndp *bool `json:"ndp,omitempty" tf:"ndp,omitempty"`

	// Maximum number of tracked connections (defaults to `262144`). Minimum value is `32768`.
	// +kubebuilder:validation:Optional
	NfConntrackMax *float64 `json:"nfConntrackMax,omitempty" tf:"nf_conntrack_max,omitempty"`

	// Conntrack established timeout in seconds (defaults to `432000` - 5 days). Minimum value is `7875`.
	// +kubebuilder:validation:Optional
	NfConntrackTCPTimeoutEstablished *float64 `json:"nfConntrackTcpTimeoutEstablished,omitempty" tf:"nf_conntrack_tcp_timeout_established,omitempty"`

	// Enable nftables based firewall (tech preview, defaults to `false`).
	// +kubebuilder:validation:Optional
	Nftables *bool `json:"nftables,omitempty" tf:"nftables,omitempty"`

	// The cluster node name.
	// +kubebuilder:validation:Optional
	NodeName *string `json:"nodeName,omitempty" tf:"node_name,omitempty"`

	// Enable SMURFS filter (defaults to `true`).
	// +kubebuilder:validation:Optional
	Nosmurfs *bool `json:"nosmurfs,omitempty" tf:"nosmurfs,omitempty"`

	// Log level for SMURFS filter. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	// +kubebuilder:validation:Optional
	SmurfLogLevel *string `json:"smurfLogLevel,omitempty" tf:"smurf_log_level,omitempty"`

	// Log level for illegal tcp flags filter. Must be one of: `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, `debug`, `nolog` (defaults to `nolog`).
	// +kubebuilder:validation:Optional
	TCPFlagsLogLevel *string `json:"tcpFlagsLogLevel,omitempty" tf:"tcp_flags_log_level,omitempty"`
}

// EnvironmentNodeFirewallSpec defines the desired state of EnvironmentNodeFirewall
type EnvironmentNodeFirewallSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EnvironmentNodeFirewallParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EnvironmentNodeFirewallInitParameters `json:"initProvider,omitempty"`
}

// EnvironmentNodeFirewallStatus defines the observed state of EnvironmentNodeFirewall.
type EnvironmentNodeFirewallStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EnvironmentNodeFirewallObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EnvironmentNodeFirewall is the Schema for the EnvironmentNodeFirewalls API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,proxmoxbpg}
type EnvironmentNodeFirewall struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeName) || (has(self.initProvider) && has(self.initProvider.nodeName))",message="spec.forProvider.nodeName is a required parameter"
	Spec   EnvironmentNodeFirewallSpec   `json:"spec"`
	Status EnvironmentNodeFirewallStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnvironmentNodeFirewallList contains a list of EnvironmentNodeFirewalls
type EnvironmentNodeFirewallList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EnvironmentNodeFirewall `json:"items"`
}

// Repository type metadata.
var (
	EnvironmentNodeFirewall_Kind             = "EnvironmentNodeFirewall"
	EnvironmentNodeFirewall_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EnvironmentNodeFirewall_Kind}.String()
	EnvironmentNodeFirewall_KindAPIVersion   = EnvironmentNodeFirewall_Kind + "." + CRDGroupVersion.String()
	EnvironmentNodeFirewall_GroupVersionKind = CRDGroupVersion.WithKind(EnvironmentNodeFirewall_Kind)
)

func init() {
	SchemeBuilder.Register(&EnvironmentNodeFirewall{}, &EnvironmentNodeFirewallList{})
}
