apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xenvironmenthagroups.virtualenv.crossplane.io
spec:
  group: virtualenv.crossplane.io
  names:
    kind: XEnvironmentHagroup
    plural: xenvironmenthagroups
  claimNames:
    kind: EnvironmentHagroup
    plural: environmenthagroups
  defaultCompositionRef:
    name: environmenthagroup-default
  connectionSecretKeys:
    - username
    - password
    - endpoint
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                group:
                  type: string
                comment:
                  type: string
                restricted:
                  type: boolean
                noFailback:
                  type: boolean
                nodes:
                  type: object
                  additionalProperties:
                    type: integer
              required:
                - group
                - nodes
