name: bpg/proxmox
resources:
    virtual_environment_user Resource - terraform-provider-proxmox:
        subCategory: ""
        description: This resource creates and manages a Proxmox virtual enviroemtn user .
        name: virtual_environment_user Resource - terraform-provider-proxmox
        title: virtual_environment_user Resource - terraform-provider-proxmox
        argumentDocs:
            acl: '- (Optional) The access control list (multiple blocks supported).'
            comment: '- (Optional) The user comment.'
            email: '- (Optional) The user''s email address.'
            enabled: '- (Optional) Whether the user account is enabled.'
            expiration_date: '- (Optional) The user account''s expiration date (RFC 3339).'
            first_name: '- (Optional) The user''s first name.'
            groups: '- (Optional) The user''s groups.'
            keys: '- (Optional) The user''s keys.'
            last_name: '- (Optional) The user''s last name.'
            password: '- (Optional) The user''s password. Required for PVE or PAM realms.'
            path: '- The path.'
            propagate: '- Whether to propagate to child paths.'
            role_id: '- The role identifier.'
            user_id: '- (Required) The user identifier.'
        importStatements: []
