//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewall) DeepCopyInto(out *EnvironmentNodeFirewall) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewall.
func (in *EnvironmentNodeFirewall) DeepCopy() *EnvironmentNodeFirewall {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentNodeFirewall) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewallInitParameters) DeepCopyInto(out *EnvironmentNodeFirewallInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LogLevelForward != nil {
		in, out := &in.LogLevelForward, &out.LogLevelForward
		*out = new(string)
		**out = **in
	}
	if in.LogLevelIn != nil {
		in, out := &in.LogLevelIn, &out.LogLevelIn
		*out = new(string)
		**out = **in
	}
	if in.LogLevelOut != nil {
		in, out := &in.LogLevelOut, &out.LogLevelOut
		*out = new(string)
		**out = **in
	}
	if in.Ndp != nil {
		in, out := &in.Ndp, &out.Ndp
		*out = new(bool)
		**out = **in
	}
	if in.NfConntrackMax != nil {
		in, out := &in.NfConntrackMax, &out.NfConntrackMax
		*out = new(float64)
		**out = **in
	}
	if in.NfConntrackTCPTimeoutEstablished != nil {
		in, out := &in.NfConntrackTCPTimeoutEstablished, &out.NfConntrackTCPTimeoutEstablished
		*out = new(float64)
		**out = **in
	}
	if in.Nftables != nil {
		in, out := &in.Nftables, &out.Nftables
		*out = new(bool)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Nosmurfs != nil {
		in, out := &in.Nosmurfs, &out.Nosmurfs
		*out = new(bool)
		**out = **in
	}
	if in.SmurfLogLevel != nil {
		in, out := &in.SmurfLogLevel, &out.SmurfLogLevel
		*out = new(string)
		**out = **in
	}
	if in.TCPFlagsLogLevel != nil {
		in, out := &in.TCPFlagsLogLevel, &out.TCPFlagsLogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewallInitParameters.
func (in *EnvironmentNodeFirewallInitParameters) DeepCopy() *EnvironmentNodeFirewallInitParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewallInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewallList) DeepCopyInto(out *EnvironmentNodeFirewallList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnvironmentNodeFirewall, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewallList.
func (in *EnvironmentNodeFirewallList) DeepCopy() *EnvironmentNodeFirewallList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewallList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentNodeFirewallList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewallObservation) DeepCopyInto(out *EnvironmentNodeFirewallObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LogLevelForward != nil {
		in, out := &in.LogLevelForward, &out.LogLevelForward
		*out = new(string)
		**out = **in
	}
	if in.LogLevelIn != nil {
		in, out := &in.LogLevelIn, &out.LogLevelIn
		*out = new(string)
		**out = **in
	}
	if in.LogLevelOut != nil {
		in, out := &in.LogLevelOut, &out.LogLevelOut
		*out = new(string)
		**out = **in
	}
	if in.Ndp != nil {
		in, out := &in.Ndp, &out.Ndp
		*out = new(bool)
		**out = **in
	}
	if in.NfConntrackMax != nil {
		in, out := &in.NfConntrackMax, &out.NfConntrackMax
		*out = new(float64)
		**out = **in
	}
	if in.NfConntrackTCPTimeoutEstablished != nil {
		in, out := &in.NfConntrackTCPTimeoutEstablished, &out.NfConntrackTCPTimeoutEstablished
		*out = new(float64)
		**out = **in
	}
	if in.Nftables != nil {
		in, out := &in.Nftables, &out.Nftables
		*out = new(bool)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Nosmurfs != nil {
		in, out := &in.Nosmurfs, &out.Nosmurfs
		*out = new(bool)
		**out = **in
	}
	if in.SmurfLogLevel != nil {
		in, out := &in.SmurfLogLevel, &out.SmurfLogLevel
		*out = new(string)
		**out = **in
	}
	if in.TCPFlagsLogLevel != nil {
		in, out := &in.TCPFlagsLogLevel, &out.TCPFlagsLogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewallObservation.
func (in *EnvironmentNodeFirewallObservation) DeepCopy() *EnvironmentNodeFirewallObservation {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewallObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewallParameters) DeepCopyInto(out *EnvironmentNodeFirewallParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LogLevelForward != nil {
		in, out := &in.LogLevelForward, &out.LogLevelForward
		*out = new(string)
		**out = **in
	}
	if in.LogLevelIn != nil {
		in, out := &in.LogLevelIn, &out.LogLevelIn
		*out = new(string)
		**out = **in
	}
	if in.LogLevelOut != nil {
		in, out := &in.LogLevelOut, &out.LogLevelOut
		*out = new(string)
		**out = **in
	}
	if in.Ndp != nil {
		in, out := &in.Ndp, &out.Ndp
		*out = new(bool)
		**out = **in
	}
	if in.NfConntrackMax != nil {
		in, out := &in.NfConntrackMax, &out.NfConntrackMax
		*out = new(float64)
		**out = **in
	}
	if in.NfConntrackTCPTimeoutEstablished != nil {
		in, out := &in.NfConntrackTCPTimeoutEstablished, &out.NfConntrackTCPTimeoutEstablished
		*out = new(float64)
		**out = **in
	}
	if in.Nftables != nil {
		in, out := &in.Nftables, &out.Nftables
		*out = new(bool)
		**out = **in
	}
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = new(string)
		**out = **in
	}
	if in.Nosmurfs != nil {
		in, out := &in.Nosmurfs, &out.Nosmurfs
		*out = new(bool)
		**out = **in
	}
	if in.SmurfLogLevel != nil {
		in, out := &in.SmurfLogLevel, &out.SmurfLogLevel
		*out = new(string)
		**out = **in
	}
	if in.TCPFlagsLogLevel != nil {
		in, out := &in.TCPFlagsLogLevel, &out.TCPFlagsLogLevel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewallParameters.
func (in *EnvironmentNodeFirewallParameters) DeepCopy() *EnvironmentNodeFirewallParameters {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewallParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewallSpec) DeepCopyInto(out *EnvironmentNodeFirewallSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewallSpec.
func (in *EnvironmentNodeFirewallSpec) DeepCopy() *EnvironmentNodeFirewallSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewallSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentNodeFirewallStatus) DeepCopyInto(out *EnvironmentNodeFirewallStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentNodeFirewallStatus.
func (in *EnvironmentNodeFirewallStatus) DeepCopy() *EnvironmentNodeFirewallStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentNodeFirewallStatus)
	in.DeepCopyInto(out)
	return out
}
