apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: environmenthagroup-default
  labels:
    provider: proxmox
    type: hagroup
spec:
  compositeTypeRef:
    apiVersion: virtualenv.crossplane.io/v1alpha1
    kind: XEnvironmentHagroup
  resources:
    - name: hagroup
      base:
        apiVersion: virtualenvironmenthagroup.crossplane.io/v1alpha1
        kind: EnvironmentHagroup
        spec:
          forProvider:
            group: example
            comment: Example HA Group
            restricted: false
            noFailback: false
            nodes:
              node1: null
              node2: 1
      patches:
        - fromFieldPath: "spec.group"
          toFieldPath: "spec.forProvider.group"
        - fromFieldPath: "spec.comment"
          toFieldPath: "spec.forProvider.comment"
        - fromFieldPath: "spec.restricted"
          toFieldPath: "spec.forProvider.restricted"
        - fromFieldPath: "spec.noFailback"
          toFieldPath: "spec.forProvider.noFailback"
        - fromFieldPath: "spec.nodes"
          toFieldPath: "spec.forProvider.nodes"
